let a = 100.987;
let b = -98;
let c = 2.5e5;
let d = 0xff;
let e = 0o10;
let f = "hello" / 2;
let g = Math.sqrt(-1);
console.log(g);
console.log(10 == "10");
console.log(NaN == NaN);
console.log(0.1 + 0.2);
let p = 0.1 + 0.2;
console.log(p.toFixed(2));
console.log(0.1 + 0.2 == 0.3);
console.log(typeof f);
let h = Math.sqrt(-1);
console.log(-100.0 / 0.0);
console.log(100 / 0);
console.log(100 / 10);
console.log("10" / 2);
console.log("hello" / 2);
console.log(typeof e, e);
console.log(typeof d, d);
console.log(typeof c, c);
console.log(typeof a, a);
console.log(typeof b, b);
console.log(Number.MAX_SAFE_INTEGER);
console.log(Number.MIN_SAFE_INTEGER);
let q = -9007199254740993;
console.log(q);
let r = 9007199254740996n;
console.log(typeof r, r);
let s = Number.isSafeInteger(9007199254740993);
console.log(s);
let name = "prathibha";
console.log(typeof name, name);
let name1 = "prathibha";
console.log(typeof name1, name1);
let name2 = `53`;
console.log(typeof name2, name2);

let Name = "JAVASCRIPT";
console.log(Name[0]);
Name[0] = "P";
console.log(Name[0]);
console.log(Name.length);
let tech = "JavaScript";
let year = 2026;
console.log(`I am learning
     ${tech.toLowerCase()} in the year ${year}`);
